---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/telbot/em.telbot.cc
    - cd $DEPLOYPATH
    - composer install --no-dev
    - composer dump-autoload --no-dev --optimize
    - php artisan optimize

